# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-10 14:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagegallery',
            options={'verbose_name': 'Gallery'},
        ),
        migrations.AlterModelTable(
            name='imagegallery',
            table='privagal_gallery_image',
        ),
    ]
