# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 11:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20160610_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagegallery',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_gallery', to='core.PrivagalImage'),
        ),
    ]
